[book]
title = "PDF Trends"
description = "The current PDF trends as of Sept 2020"
authors = ["Boris Ning"]
language = "en"

[rust]
edition = "2020"

[output.html]
mathjax-support = true
site-url = "/"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2